### ISSUE TITLE
npm install bailing early

### ISSUE THREAD

**Issue by timkelty** [callerc1/shipit-npm#4]
Have you had any issues with the install task ending early?

Here's what I'm getting:

```
Running 'npm:install' task...
Installing npm modules.
Running "node -v && cd /tmp/edwards-garment-website && npm i " on local.
@ v0.10.33
npm install complete
```

..and then it proceeds with the rest of the `shipit deploy` process
Clearly - it's not actually installing the modules.
Any idea?

**Comment by callerc1** [comment]
Hi @timkelty only just picked this up. Is this still an issue? did you try running the `npm install` on the tmp directory itself manually as a test?

**Comment by timkelty** [comment]
Yes, but I think it is something in the core: https://github.com/shipitjs/shipit/issues/57

We can close this.
