### ISSUE TITLE
shipit.config.npm.remote is false try running npm:init before npm:install

### ISSUE THREAD

**Issue by tim-field** [callerc1/shipit-npm#5]
I'm not sure what this message is getting at. I thought shipit-npm itself would call init first ?

```
Running 'npm:install' task...
shipit.config.npm.remote is false try running npm:init before npm:install
'npm:install' errored after 536 μs
```

**Comment by timbofield** [comment]
updating node & npm fixed this.

**Comment by timbofield** [comment]
Actually it didn't

**Comment by tim-field** [comment]
Its fixed in the latest commit. That first condition doesn't make much sense. 

https://github.com/callerc1/shipit-npm/commit/12e0063658ff944ebb395a7f0edadd5ce9233384#diff-edf3ff3592304bb56fae753149eb721cL19

But v.0.1.1 isn't a valid install target currently. 

```
npm ERR! argv "node" "/usr/bin/npm" "install" "shipit-npm@^0.1.1" "--save"
npm ERR! node v0.12.2
npm ERR! npm  v2.8.3
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: shipit-npm@'>=0.1.1 <0.2.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.3","0.0.4","0.0.5","0.1.0"]
```

**Comment by callerc1** [comment]
Hi @timbofield looks like i forgot to publish should be all good now.

**Comment by tim-field** [comment]
Perfect thanks!
