### ISSUE TITLE
Shippit waits for npm to finish install locally, which is good, how did you do that ?

### ISSUE THREAD

**Issue by tim-field** [callerc1/shipit-npm#6]
Not a bug, but a question :)  I'm trying to fire bower and composer tasks locally on deploy but these always complete after the deploy has happened. 

How do you get shippit to wait for npm install to finish before it deploys. The obvous answer would be a blocking task, but looking at the code it doesn't seem you are doing this ?

**Comment by callerc1** [comment]
@timbofield your correct it is in fact blocking by default (https://github.com/shipitjs/shipit-utils/commit/7eed4ec30ca49a8e4e7feea706f67a13b8e1a7a1). The blocking part is handled in the shipit-utils dependancy. see this for more details: https://github.com/callerc1/shipit-npm/pull/2

Hope that helps.

**Comment by tim-field** [comment]
Thanks!
