### ISSUE TITLE
npm_preinstall event not working with asynchronous tasks

### ISSUE THREAD

**Issue by timkelty** [callerc1/shipit-npm#8]
I haven't time to dig into the `shipit-npm` code, but here's what I'm trying to do:

```
var config = {
  npm: {
    preinstall: true,
    installFlags: '--production'
  }
}

shipit.on('npm_preinstall', function() {
  console.log('npm_pre_install');
  shipit.start('shared', function() {
    shipit.emit('npm_pre_install_complete');
  });
});
```

So, on `npm_preinstall`, I want to:
- run the `shared` task.
- when `shared` is complete, run `npm:install`

What is acutally happening is:
- `npm:preinstall` starts
- my "npm_pre_install" is logged to the console
- `npm:preinstall` finishes
- `shared` runs
- the rest of `deploy` finishes
- `npm:install` runs
- `npm:install` runs...again, and again, endlessly

```
Finished 'deploy:update' after 12 s

Running 'npm:preinstall' task...
npm_pre_install
Finished 'npm:preinstall' after 345 μs
...
Running 'shared:create-dirs' task...
...
Running 'deploy:publish' task...
...
Finished 'deploy' [ deploy:init, deploy:fetch, deploy:update, deploy:publish, deploy:clean ]
Running 'npm:install' task...
Installing npm modules.
Running "node -v && cd /home/edwards/apps/website/development/releases/20150709151848 && npm i --production" on host "edwards.fusionarydev.com".
@edwards.fusionarydev.com v0.10.37
npm install complete
Finished 'npm:install' after 2.06 s

Running 'npm:install' task...
...
Running 'npm:install' task...
...
```

Any ideas?

**Comment by timkelty** [comment]
With #9, this issue would be fixed by simply doing this in your shipit config:

```
    npm: {
      triggerEvent: 'shared',
      installFlags: '--production'
    },
```

I'm doing the same thing in [shipit-shared](https://github.com/timkelty/shipit-shared#sharedtriggerevent)

Personally, I prefer this and think it is ultimately more flexible.
Let me know what you think!

**Comment by callerc1** [comment]
fixed with https://github.com/callerc1/shipit-npm/pull/9
